--INSERT INTO STATEMENTS
INSERT INTO Walmart_Trustpilot_Reviews
SELECT [reviewer_name]
      ,CASE WHEN [review_time] = 'not found' THEN NULL ELSE CAST (review_time AS datetime) END
      ,[star_rating]
      ,[headline]
      ,[review_content]
      ,CASE WHEN [experience_time] = 'not found' THEN NULL ELSE CAST (experience_time AS datetime) END
FROM STAGING.Walmart_Trustpilot_Reviews;

INSERT INTO Products
SELECT * FROM STAGING.Products;

INSERT INTO Geolocations
SElECT geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state FROM (
SELECT GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG, GEOLOCATION_CITY, GEOLOCATION_STATE, ROW_NUMBER() OVER (PARTITION BY GEOLOCATION_ZIP_CODE_PREFIX ORDER BY GEOLOCATION_ZIP_CODE_PREFIX) AS ROWN
FROM STAGING.GEOLOCATIONS) AS A
WHERE ROWN = 1

INSERT INTO Customers
SELECT * FROM STAGING.Customers;

INSERT INTO SELLERS
SELECT * FROM STAGING.SELLERS;

INSERT INTO ORDERS
SELECT * FROM STAGING.ORDERS;

INSERT INTO PAYMENTS (ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_INSTALLMENTS, PAYMENT_VALUE)
SELECT ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_INSTALLMENTS, PAYMENT_VALUE
FROM STAGING.PAYMENTS;

INSERT INTO Order_items
SELECT * FROM STAGING.Order_items;